In [3]:
import pandas as pd

In [4]:
df_all_stock = pd.read_parquet(f"../../stock_data/df_all_stock_test.parquet")

In [8]:
df_all_stock.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,...,pre_close_qfq,up_limit_qfq,down_limit_qfq,open_hfq,high_hfq,low_hfq,close_hfq,pre_close_hfq,up_limit_hfq,down_limit_hfq
0,000001.SZ,2026-01-05,11.42,11.51,11.41,11.50,11.41,0.09,0.7888,875491.18,...,11.41,12.55,10.27,61.439007,61.923202,61.385207,61.869402,61.385207,67.518348,55.252066
1,000001.SZ,2026-01-06,11.50,11.68,11.48,11.67,11.50,0.17,1.4783,1304648.42,...,11.50,12.65,10.35,61.869402,62.837793,61.761803,62.783994,61.869402,68.056343,55.682462
2,000001.SZ,2026-01-07,11.66,11.82,11.62,11.64,11.67,-0.03,-0.2571,966236.24,...,11.67,12.84,10.50,62.730194,63.590986,62.514996,62.622595,62.783994,69.078533,56.489454
3,000001.SZ,2026-01-08,11.64,11.65,11.49,11.51,11.64,-0.13,-1.1168,1100085.11,...,11.64,12.80,10.48,62.622595,62.676395,61.815603,61.923202,62.622595,68.863335,56.381855
4,000001.SZ,2026-01-09,11.53,11.53,11.44,11.46,11.51,-0.05,-0.4344,983390.04,...,11.51,12.66,10.36,62.030801,62.030801,61.546605,61.654204,61.923202,68.110142,55.736262

In [ ]:
print(df_all_stock.trade_date.unique())

<DatetimeArray>
['2026-01-05 00:00:00', '2026-01-06 00:00:00', '2026-01-07 00:00:00',
 '2026-01-08 00:00:00', '2026-01-09 00:00:00', '2026-01-12 00:00:00',
 '2026-01-13 00:00:00', '2026-01-14 00:00:00', '2026-01-15 00:00:00',
 '2026-01-16 00:00:00', '2026-01-19 00:00:00', '2026-01-20 00:00:00',
 '2026-01-21 00:00:00', '2026-01-22 00:00:00', '2026-01-23 00:00:00',
 '2026-01-26 00:00:00', '2026-01-27 00:00:00', '2026-01-28 00:00:00',
 '2026-01-29 00:00:00', '2026-01-30 00:00:00', '2026-02-02 00:00:00',
 '2026-02-03 00:00:00', '2026-02-04 00:00:00']
Length: 23, dtype: datetime64[ns]

In [11]:
df_all = pd.read_parquet(f"../../stock_data/df_all_stock.parquet")
df_all.tail()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,...,pre_close_qfq,up_limit_qfq,down_limit_qfq,open_hfq,high_hfq,low_hfq,close_hfq,pre_close_hfq,up_limit_hfq,down_limit_hfq
15693875,920992.BJ,2026-01-23,18.81,19.10,18.70,18.86,18.71,0.15,0.8017,13771.14,...,18.71,24.32,13.10,19.432055,19.731645,19.318417,19.483708,19.328748,25.124273,13.533223
15693876,920992.BJ,2026-01-26,18.81,18.95,18.38,18.62,18.86,-0.24,-1.2725,13815.54,...,18.86,24.51,13.21,19.432055,19.576685,18.987835,19.235771,19.483708,25.320556,13.646860
15693877,920992.BJ,2026-01-27,18.62,18.79,17.80,18.20,18.62,-0.42,-2.2556,16014.04,...,18.62,24.20,13.04,19.235771,19.411393,18.388654,18.801882,19.235771,25.000304,13.471238
15693878,920992.BJ,2026-01-28,18.17,18.25,17.81,17.95,18.20,-0.25,-1.3736,11614.64,...,18.20,23.66,12.74,18.770890,18.853535,18.398984,18.543614,18.801882,24.442446,13.161317
15693879,920992.BJ,2026-01-29,18.00,18.13,17.62,17.62,17.95,-0.33,-1.8384,13291.72,...,17.95,23.33,12.57,18.595268,18.729567,18.202701,18.202701,18.543614,24.101533,12.985695